### ISSUE TITLE
[feature request] multiple account support

### ISSUE THREAD

**Issue by ccddos** [BenderBlog/traintime_pda#60]
"Some users need to access multiple classes across two accounts.

 Could you please add account switch feature?"

**Comment by BenderBlog** [comment]
I need a clear and reasonable reason, since it is another very difficult function. You see, every stuff in my program is relying on a single account. Add multiple account switch feature will make everything very complex, way more complex than GetX can handle. It will beyond my, a dunky robot who enter some woman's blacklist, and a postgraduate, control.

The only thing I could consider is the pre-post graduate classes, which school provided another account. But I believe it doesnot need dual-account, I just simply made an entry to fetch it from the setting. I have had enough of the add user defined class function, which brokes every day. So I won't recommend that.

If you want to login your partner's account, assume you have, use "Partner Classtable" function.

Thanks for you reading this, hope you can understand me:P

**Comment by ccddos** [comment]
Got it.  You are right.

Considering hard to achieve it in code level, I will simple achieve by using dual app on android.
